### ISSUE TITLE
phina.ui.GaugeのcornerRadiusが反映されない

### ISSUE THREAD

**Issue by tsumac** [phinajs/phina.js#159]
本来 `fillRoundRect` であるべき箇所が `fillRect` になってたりします。
v0.1.2の10300行目あたりです。

**Comment by simiraaaa** [comment]
サンプル
http://goo.gl/ZmKoEX
現在開発中のバージョンでは修正済みですので、最新版を使っていただくか、
0.2.0のリリースをお待ち下さい。

**Comment by phi-jp** [comment]
@tsumac san
@simiraaaa san の言うように次のバージョンでは修正済みです.
お手数かけますmm
