### ISSUE TITLE
当たり判定も考慮したオブジェクトのグルーピング機能

### ISSUE THREAD

**Issue by alkn203** [phinajs/phina.js#185]
* パワポ資料とか作っていると図形などをグループ化したり解除したりするイメージ。
* グループ化したら当たり判定もまとめられて１つになる。

以下コメント

* bounding type に group とか作る。
* DisplayElementに当たり判定のサイズを設定してBoundingType設定。

**Comment by phi-jp** [comment]
memo: ダブルクリックしたら子供選択できるようにする的な♪

**Comment by alkn203** [comment]
今見ると自分でも必要性が感じないので、クローズ。
