### ISSUE TITLE
FlowのthenでFlow以外を返す時の挙動がおかしいことがある

### ISSUE THREAD

**Issue by negiwine** [phinajs/phina.js#232]
初めまして。@Negiwineといいます。
Flowでおそらく意図しない動作があったので報告します。確認したのはv0.2.2です。

次のコードで、初めのthenで`10`を返しても次のthenに`10`ではなく`20`が渡ってしまいます。
```js
Flow(function(resolve, reject){
  setTimeout(resolve, 1, 20);
})
.then(function(){ return 10; })
.then(function(arg){
  console.log('Flow: '+arg); //'Flow: 20'
});
```

Flow.resolveで始めたときは正常に`10`が渡ります。
```js
Flow.resolve(20)
  .then(function(){ return 10; })
  .then(function(arg){
    console.log('Flow2: '+arg); //'Flow: 10'
  });
```

こちらは[runstantでの確認](http://runstant.com/Negiwine/projects/97e8bfdc)です。
おそらく[この行](https://github.com/phinajs/phina.js/blob/v0.2.2/src/util/flow.js#L82)でresultValueでなくargを渡しているのが原因かと思いますが、不慣れなもので報告だけさせていただきます。

**Comment by negiwine** [comment]
#248 でマージしていただけたのでcloseします。
対応ありがとうございました。

**Comment by phi-jp** [comment]
@negiwine いえいえ遅くなってすみませんでしたmm
