### ISSUE TITLE
Label / LabelAreaでの自動改行

### ISSUE THREAD

**Issue by altkaye** [phinajs/phina.js#37]
tmlib 0.5.2のLabelAreaでは'あ'というフォント幅で測定していて、プロポーショナルフォントだと幅が短い文字で改行位置がずれる問題あり.

tmlibの最新buildでは解決済みだが、これと同様に、phinaでもフォント幅を計算して自動改行する機能を搭載するかどうか.

また、本機能はLabel / LabelAreaどちらで実装するべきか

**Comment by phi-jp** [comment]
thx

**Comment by simiraaaa** [comment]
自動改行はLabelでやって
LabelAreaでは飽くまでLabelをDOMのTextAreaみたいに扱うという方が自分は良いかなと思います

**Comment by simiraaaa** [comment]
Labelには自動改行機能をつけずに、Labelを継承してLabelAreaで自動改行機能をつけます。
描画範囲は width, heightの範囲内になり、
verticalAlign = 'top' 上から描画 'center' 'middle' 中心から描画 'bottom' 下から描画
という仕様で実装してみます。

**Comment by phi-jp** [comment]
@simiraaaa san ありがとうございます!!

**Comment by simiraaaa** [comment]
scrollX = 横軸のoffset
scrollY = 縦軸のoffset
align = left 左寄せ 見た目は一番左の文字が scrollX + x - width/2の位置になる
align = right 右寄せ 見た目は一番右の文字が scrollX + x + width/2の位置になる

verticalAlign = top (-0.5)
上詰め 一番上の文字が  中心(0) から scrollY + height * verticalAlign の位置になる

verticalAlign = bottom (0.5)
下詰め 一番下の文字が  中心(0) から scrollY + height * verticalAlign の位置になる

verticalAlign = Number　中心から任意の割合ずらした位置

**Comment by simiraaaa** [comment]
http://goo.gl/Vctw0A

**Comment by simiraaaa** [comment]
ちょっと変えました
http://goo.gl/6gTTX6
自動改行部分のコードは tmlibの時とほぼ同じです。

**Comment by simiraaaa** [comment]
http://goo.gl/Vo9Qqw
これで、ほぼ問題はないかなと思います。
定期的に改行が入れば10万文字ぐらいでもそこそこ速度出ます

**Comment by simiraaaa** [comment]
http://goo.gl/u9riO4
キャッシュのサイズ節約と高速化しました。
改行がない連続する100万文字でもそこそこ速度出ます
![image](https://cloud.githubusercontent.com/assets/8247441/12633434/20a9ee30-c5b5-11e5-91a7-61814353e905.png)

**Comment by phi-jp** [comment]
@simiraaaa san
素晴らしい!!
結構いろいろやってますね.
