### ISSUE TITLE
assetLoadFunctions に file の読み込み処理を追加

### ISSUE THREAD

**Issue by fukuyama** [phinajs/phina.js#66]
phina.asset.File はあるけど、assetLoadFunctions に file のロード機能がなかったので追加。

拡張子で自動的に判断するか

``` javascript
assets: {
  file: {
    path: "http://foo/bar.json",
    dataType: "json"
  }
}
```

と、dataType で頑張るか…

もしくは、"file" 以外に、"json" や "xml" を増やしていくか、検討が必要かも。

**Comment by fukuyama** [comment]
とりあえず作ったのは、こんな感じです。

https://github.com/fukuyama/phina.js/commit/c15a69ccb5cf6b3fbf3cda6bea21fdfa8b082bf3

**Comment by phi-jp** [comment]
@fukuyama san

> もしくは、"file" 以外に、"json" や "xml" を増やしていくか、

自分はこっちが好みですね.
データの見通しもよくなりますし♪

**Comment by fukuyama** [comment]
image とか font もファイルじゃんって思いなおしたんですよねｗ
json とか xml に :+1:

**Comment by phi-jp** [comment]
じゃ text っすかね？w

**Comment by fukuyama** [comment]
テキストベースの assetLoadFunctions をどれくらい用意するかは悩みますね。 
html / yaml / md などなど… mime type 的にテキスト系のものは多い感じ。

最悪、追加するのは簡単なので、json / xml / text とか代表的なのがあればよさそ。
もしくは、ほしいとかリクエストとかニーズがあったときに追加でも。

**Comment by phi-jp** [comment]
@fukuyama san json / xml / text までで良いと思いますね.
yaml とか md とか本格的にサポートしようとすると外部ライブラリに依存しちゃうので...
