### ISSUE TITLE
ベクトルから向きを文字列で取得できるようにする

### ISSUE THREAD

**Issue by phi-jp** [phinajs/phina.js#69]
```
var d = v.getDirectionString(); // 'left' or 'right' or 'up' or 'down' 的な
```

フリックで操作するときなどに使える!!

**Comment by alkn203** [comment]
updateとかで動かしている時も、移動方向を一発で得たいなと思う時があるのですが、その辺りにも使えるイメージですか？
普段は、例えば直前のx座標を別途記録しておいて、現在のx座標との差が正か負かで判定したりしてます。

**Comment by phi-jp** [comment]
@simiraaaa san
それって deltaPosition じゃダメですかね？
http://goo.gl/CHQzgD

**Comment by alkn203** [comment]
@simiraaaa さんじゃないですよ～（笑）
pointerの場合はそれで良いと思います。
今回は、updateで
x += vx;
y +=vy;
とかやって動かしている場合のことを言いたかったのですが、良く考えたらvxとかに自分で入れちゃってるので
あまり意味はないなと思いました。なので、このままで特に支障はないです。お騒がせしました。

**Comment by phi-jp** [comment]
@alkn203 あっ失礼しましたmm

あれ？自分の理解不足ですかね？？
イマイチピンと来てないです.

ちなみに前の座標は prevPosition で取れます.

- postion ... 今の座標(or x, y)
- prevPosition ... 前の座標
- deltaPosition ... 前の座標と今の座標の差分(dx, dy)

**Comment by alkn203** [comment]
了解です。何か自分でも混乱してきたので、もう一度頭の整理しますw
ありがとうございました♪

**Comment by phi-jp** [comment]
getDirection メソッド作るかなぁ
